### ISSUE TITLE
Suggestion: Add a green dot for completed lessons

### ISSUE THREAD

**Issue by halspeed** [microbit-foundation/microbit-swift-playgrounds#10] opened 2018-06-25 05:12 UTC
Apple suggested adding a green dot to the list navigation after the completion of a lesson

**Comment by gary-atkinson** [comment] 2018-06-25 10:38
Duplicate of #9

**Comment by jaustin** [comment] 2018-06-29 11:36
Closing as part of triage, will respond on #9

**Closed by jaustin** 2018-06-29 11:36 UTC
